import Header from "./components/Header";

import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import "./styles/dotGridLayout.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased dot-grid`}>
        <Header />
        <div className="dot-grid-container container-xl">{children}</div>
      </body>
    </html>
  );
}
